language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install -r requirements.txt --use-mirrors
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]]; then sudo apt-get install -qq python3-nose; fi

script:
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]]; then nosetests3; else nosetests; fi
