language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - sudo apt-get install -qq python3-nose
  - pip install -r requirements.txt --use-mirrors
  - export NOSETESTS=nosetests; if [[ "3" == $(python -c "import sys; sys.stdout.write(str(sys.version_info.major))") ]]; then export NOSETESTS=nosetests3; fi

script:
  - $NOSETESTS
